enableImmutableInstalls: false

nodeLinker: node-modules

npmScopes:
  awesome.me:
    npmAlwaysAuth: true
    npmAuthToken: '${FONTAWESOME_PACKAGE_TOKEN}'
    npmRegistryServer: 'https://npm.fontawesome.com/'
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: '${FONTAWESOME_PACKAGE_TOKEN}'
    npmRegistryServer: 'https://npm.fontawesome.com/'

yarnPath: .yarn/releases/yarn-4.8.1.cjs
