title: The Red Journey
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://unicolo.red' # the base hostname & protocol for your site, e.g. http://example.com
domain: unicolo.red
description: >- # this means to ignore newlines until "baseurl:"
  Hey there! I’m Gilles, aka unicolored—a creative developer painting my journey
  red with code, ideas, and life.
twitter_username: gilleshoarau
github_username: unicolored
rss: rss
collections_dir: contents
collections:
  projects:
    output: true
safe: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-meilisearch
postcss:
  cache: false
exclude:
  - .idea
  - bin
  - package.json
  - package-lock.json

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      description:
      image:
      category:
      tags:
      published: false
      sitemap: false

meilisearch:
  disable_in_development: true
  url: 'http://localhost:7700'
  api_key: 'b3f0f337267b9fda8d9e39a1975ccc96c8003bd25ad6ddaa058cf67dd19c0fc6'
  search_api_key: '8a7690949055fe1bc7af81b8ef6972ad02ff372b158118ef9316f7e41f89159f'
  index_name: 'unicolored_dev'
  collections:
    posts:
      fields:
        - title
        - content
        - url
        - category
        - tags

analytics:
  id: '3dd19a25-088b-4c23-a7ea-d7b76c59b71e'
  enabled: true
