title: The Red Journey
baseurl: ''
host: 'localhost'
port: 4125
safe: true
url: 'https://unicolored.com' # the base hostname & protocol for your site, e.g. http://example.com
domain: unicolored.com
#description: >- # this means to ignore newlines
#  Hey there! I’m Gilles, aka unicolored—a creative developer painting my journey
#  red with code, ideas, and life.
twitter_username: gilleshoarau
github_username: unicolored
nav_pages:
  - projects.html
  - about.html
rss: rss
collections_dir: contents
collections:
  projects:
    output: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-meilisearch
postcss:
  cache: false
exclude:
  - .idea
  - bin
  - package.json
  - package-lock.json

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      description:
      image:
      category:
      tags:
      published: false
      sitemap: false

meilisearch:
  disable_in_development: true
  url: 'http://localhost:7700'
  api_key: '7b87f0a5fc0e08bec43f2d4ea996534caa52a898a85eaca287d064284d69dcec'
  search_api_key: 'c880ba40824b129bff98617169edcedcd7beecc3facb092d7501430147d65127'
  index_name: 'unicolored_dev'
  collections:
    posts:
      fields:
        - title
        - content
        - url
        - category
        - tags

analytics:
  id: '3dd19a25-088b-4c23-a7ea-d7b76c59b71e'
  enabled: true
