name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
      NODE_ENV: development
      FONTAWESOME_PACKAGE_TOKEN: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}
      MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
      MEILISEARCH_SEARCH_API_KEY: ${{ secrets.MEILISEARCH_SEARCH_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '23'
      - run: |
          corepack enable
          corepack prepare yarn@stable --activate
      - run: yarn install
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - run: |
          echo "meilisearch:" > _config.secrets.yml
          echo "  api_key: $MEILISEARCH_API_KEY" >> _config.secrets.yml
          echo "  search_api_key: $MEILISEARCH_SEARCH_API_KEY" >> _config.secrets.yml

      - run: sh script/cibuild.sh

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
